import './globals.css'
import { Sarabun, Space_Mono } from 'next/font/google'

const sarabun = Sarabun({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-sarabun',
  display: 'swap',
})

const space_mono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sarabun.variable} ${space_mono.variable}`} >
      <head>
        <link rel="icon" href="/formmi.ico" sizes="any" />
      </head>
      <body 
        className={'relative'}
      >
        {children}
      </body>
    </html>
  )
}
